"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";

import Globe from "./GlobeWrapper";
import Sidebar from "./Sidebar";
import SystemButtons from "./SystemButtons";
import LoadingScreen from "./LoadingScreen";
import SplashScreen from "./SplashScreen";
import CableInformation from "./CableInformation";
import GeneralInformation from "./GeneralInformation";
import { Header } from "./Header";
import { LanguageToggle } from "./LanguageToggle";
import { RecenterButton } from "./RecenterButton";
import { RightCluster } from "./RightCluster";
import { ClusterStem } from "./ClusterStem";
import {
  CALLOUT_BOX_HEIGHT,
  CALLOUT_REST_RISE,
  CALLOUT_WIDTH,
  LandingPointCallout,
} from "./LandingPointCallout";
import HowToGuideDialog from "./HowToGuideDialog";
import FunFactDialog from "./FunFactDialog";
import MorseCodePop from "./MorseCodePop";

import { cables, cablesById } from "@/data/cables";
import { landingPoints } from "@/data/landingPoints";
import { cableRoutes } from "@/data/cableRoutes";
import countries from "@/data/countries.json";
import robotoMedium from "@/data/roboto-medium.typeface.json";

import type {
  CableSystem,
  DialogId,
  Language,
  LandingPoint,
} from "@/lib/types";
import { V1_COLORS, CABLE_COLORS } from "@/lib/colors";
import { resolveCallRoute } from "@/lib/callRoutes";
import {
  playConnect,
  playDialing,
  playMessage,
  setMuted as setAudioMuted,
} from "@/lib/morseAudio";
import { useIdleAttractor } from "@/lib/useIdleAttractor";
import { useT } from "@/lib/i18n";

// ───────── Tuning ─────────

// Travelling-dot tuning — constant world-size spheres along every cable.
const DOT_RADIUS = 0.11;
const DOT_SPEED_KM_PER_SEC = 375;
const DOT_MIN_LOOP_SEC = 4;

// Quantized zoom buckets — three-globe rebuilds TextGeometry whenever
// labelSize / labelDotRadius returns a new value. A continuous scalar from
// piecewiseByZoom triggers ~163 dispose+tessellate-glyph-paths per zoom tick →
// catastrophic stutter. Buckets cap rebuilds at one per threshold crossing.
type ZoomBucket = 0 | 1 | 2 | 3 | 4 | 5;
const bucketForAltitude = (alt: number): ZoomBucket => {
  if (alt >= 1.5) return 0;
  if (alt >= 1.2) return 1;
  if (alt >= 0.35) return 2;
  if (alt >= 0.1) return 3;
  if (alt >= 0.02) return 4;
  return 5;
};
const POINT_RADIUS_BY_BUCKET = [0, 0, 0.06, 0.04, 0.025, 0.025] as const;
// Cable glow width multiplier per zoom bucket (0 = far, 5 = closest). Bucketed
// rather than computed from raw altitude so the path-stroke accessor only
// changes identity on a bucket crossing — avoids re-tessellating every path on
// each zoom poll. Grows as you zoom in so the neon glow keeps constant visual
// thickness instead of appearing to shrink.
const GLOW_SCALE_BY_BUCKET = [1.0, 1.3, 1.7, 2.1, 2.4, 2.6] as const;
// Horizontal placement of the globe's centre as a fraction of viewport width.
// 0.5 = dead-centre; we push it left so the sphere sits between the left edge
// and the Cable System panel, leaving room on the right for the panels.
// The canvas is translated by this offset and the callout/label projections
// add the same offset so they stay locked to the sphere.
const GLOBE_CENTER_FRAC = 0.4;
const globeOffsetX = (width: number) => (GLOBE_CENTER_FRAC - 0.5) * width;

// City labels: one threshold instead of buckets. Above it cities vanish.
// Below, geometry is built once and a per-frame scaler handles fade-in + a
// sqrt shrink with altitude (keeps labels visible at very close zoom).
const CITY_LABEL_BASE_SIZE = 0.13;
const CITY_VISIBLE_ALT = 0.314;
const CITY_FADE_BAND = 0.05;
const CITY_REF_ALT = CITY_VISIBLE_ALT - CITY_FADE_BAND;
const CITY_MIN_SCALE = 0.18;
const cityScaleAt = (alt: number): number => {
  if (alt >= CITY_VISIBLE_ALT) return 0;
  const fade = Math.min(1, (CITY_VISIBLE_ALT - alt) / CITY_FADE_BAND);
  const shrink = Math.max(
    CITY_MIN_SCALE,
    Math.sqrt(Math.max(0, alt) / CITY_REF_ALT),
  );
  return fade * shrink;
};

// Country labels: mirror of the city pattern, but inverted. Fade OUT as you
// zoom in past a threshold; visible above with sqrt shrink so big country
// names don't dominate at mid-zoom.
const COUNTRY_LABEL_BASE_SIZE = 0.85;
const COUNTRY_HIDDEN_ALT = 0.2;
const COUNTRY_FADE_BAND = 0.1;
const COUNTRY_REF_ALT = 1.5;
const countryScaleAt = (alt: number): number => {
  if (alt <= COUNTRY_HIDDEN_ALT) return 0;
  const fade = Math.min(1, (alt - COUNTRY_HIDDEN_ALT) / COUNTRY_FADE_BAND);
  const shrink = Math.min(1, Math.sqrt(alt / COUNTRY_REF_ALT));
  return fade * shrink;
};

// ───────── Static assets ─────────

// Pre-baked equirectangular dark world map (sea + land + country strokes).
// Generated by scripts/generate-world-map.mjs. Replaces tile streaming so the
// kiosk works fully offline. Light variant + outline-mode + texture-mode all
// removed in v1.0 (resolution §H.11 = dark only, §H.1 = re-skin).
const WORLD_MAP_DARK_URL = "/textures/world-mono-dark.webp";

// Regional sharpness overlay — 4K bake over the SEA window (~1.2 km/texel vs
// ~5 km for the global). One grid-mesh draw call, fades in at close zoom.
const SEA_OVERLAY_DARK_URL = "/textures/world-mono-dark-sea.webp";
const SEA_LAT_MIN = -15;
const SEA_LAT_MAX = 25;
const SEA_LNG_MIN = 90;
const SEA_LNG_MAX = 130;
const SEA_GRID = 32;
const SEA_OVERLAY_ALT = 0.0008;
const SEA_FADE_IN_ALT = 0.6;
const SEA_FADE_OUT_ALT = 0.3;

// ───────── v1.0 palette → globe constants ─────────

const ATMOSPHERE_COLOR = V1_COLORS.atmosphere;          // #034DA1 v1-blue
const CABLE_SELECTED_COLOR = V1_COLORS.cableSelected;   // #ED1B2E
const CABLE_MUTED_COLOR = V1_COLORS.cableMuted;         // rgba(255,255,255,0.30)
// Neon glow (both default + selected): one saturated colour ring hugging the
// white-hot core.
const CABLE_HALO_DEFAULT_OUTER_ALPHA = 0.15; // saturated colour glow around core


const hexToRgb = (hex: string): [number, number, number] => {
  const h = hex.replace("#", "");
  const full =
    h.length === 3
      ? h.split("").map((c) => c + c).join("")
      : h;
  return [
    parseInt(full.slice(0, 2), 16),
    parseInt(full.slice(2, 4), 16),
    parseInt(full.slice(4, 6), 16),
  ];
};
const hexToRgba = (hex: string, alpha: number) => {
  const [r, g, b] = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
};
// Neon "hot filament" core — push the identity colour most of the way to white
// so the centre of the line reads as a bright lit core (lightsaber style),
// leaving the saturated colour to live in the surrounding glow.
const neonCore = (hex: string, toward = 0.72) => {
  const [r, g, b] = hexToRgb(hex);
  const mix = (c: number) => Math.round(c + (255 - c) * toward);
  return `rgb(${mix(r)}, ${mix(g)}, ${mix(b)})`;
};
const LANDING_POINT_DEFAULT = V1_COLORS.fg;             // white
const LANDING_POINT_ACTIVE = V1_COLORS.active;          // #8FFF3F lime
const LANDING_POINT_MUTED = "rgba(120, 120, 120, 0.30)";
const TRAVELLING_DOT_COLOR = V1_COLORS.fg;              // white

// Default + Malaysia-recenter coordinates.
const DEFAULT_LAT = 5;
const DEFAULT_LNG = 108;
const DEFAULT_ALT = 2.2;
const MY_LAT = 4.2105;
const MY_LNG = 101.9758;
const MY_ALT = 2.2;

// Tooltip styling for the built-in pointLabel / pathLabel render.
const TOOLTIP_STYLE =
  "padding:6px 10px;background:rgba(4,14,31,0.92);border:1px solid rgba(255,255,255,0.40);color:#FFFFFF;font-size:12px;font-family:'Rajdhani','Helvetica Neue',sans-serif;font-weight:600;letter-spacing:0.04em;";
const renderPathLabel = (path: any) =>
  `<div style="${TOOLTIP_STYLE}">${path.name}</div>`;
const renderPointLabel = (p: any) =>
  `<div style="${TOOLTIP_STYLE}">${p.city}, ${p.country}</div>`;

interface PathData {
  coords: [number, number][];
  cableId: string;
  name: string;
  color: string;
  status: CableSystem["status"];
  // Neon glow ring index: undefined = white-hot core line,
  // 2 = saturated colour glow hugging the core.
  _halo?: 2;
}

export default function GlobeScene() {
  const globeRef = useRef<any>(null);
  const [isLoaded, setIsLoaded] = useState(false);
  // Intro splash: shown AFTER the loading screen finishes (isLoaded → true),
  // held ~3.5s then faded out to reveal the globe. Order: loading → splash →
  // globe. `splashFading` triggers the fade-out before unmount.
  const [showSplash, setShowSplash] = useState(true);
  const [splashFading, setSplashFading] = useState(false);
  // Keep the loading screen mounted under the splash until the splash has
  // fully faded in, so the #040E1F backdrop never breaks during the crossfade.
  const [hideLoading, setHideLoading] = useState(false);
  const [selectedCable, setSelectedCable] = useState<CableSystem | null>(null);
  const [selectedLandingPoint, setSelectedLandingPoint] =
    useState<LandingPoint | null>(null);
  /** Screen-space position of every landing point along the selected cable —
      keyed by point id. Used to position the per-point callouts. */
  const [calloutScreens, setCalloutScreens] = useState<
    Record<string, { x: number; y: number; visible: boolean }>
  >({});
  const [openDialog, setOpenDialog] = useState<DialogId>(null);
  const [expandedPointId, setExpandedPointId] = useState<string | null>(null);
  const [language, setLanguage] = useState<Language>("en");
  const [muted, setMuted] = useState(false);
  const [dimensions, setDimensions] = useState({ width: 0, height: 0 });
  const [zoomLevel, setZoomLevel] = useState(DEFAULT_ALT);
  const [autoRotate, setAutoRotate] = useState(false);
  const [activeCall, setActiveCall] = useState<{
    message: string;
    startedAt: number;
  } | null>(null);

  // Idle attractor (§H.12): after ~60s of no interaction, slow auto-rotate
  // kicks in and a "TAP ANYWHERE TO BEGIN" hint appears. Any touch dismisses.
  const isIdle = useIdleAttractor(60_000);
  const t = useT(language);

  // Push mute state down to morseAudio so playDot/playMessage/etc no-op.
  useEffect(() => {
    setAudioMuted(muted);
  }, [muted]);

  // Idle → enable auto-rotate and close any open dialog so the attractor
  // doesn't end up rendered behind a modal nobody is around to dismiss.
  useEffect(() => {
    if (isIdle) {
      setAutoRotate(true);
      setOpenDialog(null);
      setSelectedCable(null);
      setSelectedLandingPoint(null);
      setExpandedPointId(null);
    } else {
      setAutoRotate(false);
    }
  }, [isIdle]);

  // Resize handler
  useEffect(() => {
    const update = () =>
      setDimensions({ width: window.innerWidth, height: window.innerHeight });
    update();
    window.addEventListener("resize", update);
    return () => window.removeEventListener("resize", update);
  }, []);

  // Solid line per segment. Travelling dots are NOT in this list — they're
  // real THREE.Mesh spheres added directly to the scene (see RAF effect).
  const pathsData: PathData[] = useMemo(() => {
    const out: PathData[] = [];
    for (const route of cableRoutes) {
      const cable = cablesById[route.cableId];
      const baseColor = CABLE_COLORS[route.cableId] || "#ffffff";
      const status = cable?.status ?? "active";
      const colorByStatus =
        status === "retired" || status === "inactive"
          ? V1_COLORS.mute // #C4C4C4 — dim grey, but glows like the rest
          : status === "planned"
            ? V1_COLORS.orange
            : baseColor;
      for (const seg of route.segments) {
        out.push({
          coords: seg.coords,
          cableId: route.cableId,
          name: cable?.shortName || route.cableId,
          color: colorByStatus,
          status,
        });
      }
    }
    return out;
  }, []);

  // Per-segment cumulative arc-length (km) so the travelling-dot RAF can map
  // elapsed time → distance → lat/lng.
  const dotSegments = useMemo(() => {
    const haversine = (a: [number, number], b: [number, number]) => {
      const R = 6371;
      const dLat = ((b[0] - a[0]) * Math.PI) / 180;
      const dLng = ((b[1] - a[1]) * Math.PI) / 180;
      const la1 = (a[0] * Math.PI) / 180;
      const la2 = (b[0] * Math.PI) / 180;
      const x =
        Math.sin(dLat / 2) ** 2 +
        Math.cos(la1) * Math.cos(la2) * Math.sin(dLng / 2) ** 2;
      return 2 * R * Math.asin(Math.sqrt(x));
    };
    type Seg = {
      coords: [number, number][];
      cumKm: number[];
      totalKm: number;
    };
    const segs: Seg[] = [];
    for (const route of cableRoutes) {
      for (const seg of route.segments) {
        const coords = seg.coords;
        if (coords.length < 2) continue;
        const cumKm = [0];
        for (let i = 1; i < coords.length; i++) {
          cumKm.push(cumKm[i - 1] + haversine(coords[i - 1], coords[i]));
        }
        segs.push({ coords, cumKm, totalKm: cumKm[cumKm.length - 1] });
      }
    }
    return segs;
  }, []);

  // Greedy cluster: any landing points within CLUSTER_KM of an existing
  // cluster centroid get merged. Avoids stacked dots/labels for near-duplicate
  // sites (Sedili CLS1+CLS2, Katong/East Coast, etc.).
  const CLUSTER_KM = 6;
  const pointClusters = useMemo(() => {
    const haversine = (
      a: { lat: number; lng: number },
      b: { lat: number; lng: number },
    ) => {
      const R = 6371;
      const dLat = ((b.lat - a.lat) * Math.PI) / 180;
      const dLng = ((b.lng - a.lng) * Math.PI) / 180;
      const la1 = (a.lat * Math.PI) / 180;
      const la2 = (b.lat * Math.PI) / 180;
      const x =
        Math.sin(dLat / 2) ** 2 +
        Math.cos(la1) * Math.cos(la2) * Math.sin(dLng / 2) ** 2;
      return 2 * R * Math.asin(Math.sqrt(x));
    };
    type Cluster = {
      lat: number;
      lng: number;
      members: typeof landingPoints;
    };
    const result: Cluster[] = [];
    for (const p of landingPoints) {
      const c = result.find((c) => haversine(c, p) < CLUSTER_KM);
      if (c) {
        c.members.push(p);
        c.lat = c.members.reduce((s, m) => s + m.lat, 0) / c.members.length;
        c.lng = c.members.reduce((s, m) => s + m.lng, 0) / c.members.length;
      } else {
        result.push({ lat: p.lat, lng: p.lng, members: [p] });
      }
    }
    return result;
  }, []);

  // Switch between clustered (far/mid zoom) and individual (close zoom) points.
  const useClusters = zoomLevel > 0.18;

  const pointsData = useMemo(() => {
    if (!useClusters) {
      return landingPoints.map((p) => ({
        ...p,
        memberIds: [p.id],
        size: 0.4,
        color: LANDING_POINT_DEFAULT,
      }));
    }
    return pointClusters.map((c) => {
      const ids = c.members.map((m) => m.id);
      const cities = Array.from(new Set(c.members.map((m) => m.city)));
      const cableIds = Array.from(
        new Set(c.members.flatMap((m) => m.cableIds)),
      );
      return {
        id: ids.join("+"),
        name: c.members[0].name,
        city: cities.join(" / "),
        country: c.members[0].country,
        region: c.members[0].region,
        lat: c.lat,
        lng: c.lng,
        cableIds,
        memberIds: ids,
        size: 0.4,
        color: LANDING_POINT_DEFAULT,
      };
    });
  }, [useClusters, pointClusters]);

  // Country labels — pick the largest polygon per feature so MultiPolygon
  // countries label on their main body, not a stray island.
  const countryLabels = useMemo(() => {
    const out: { lat: number; lng: number; name: string; area: number }[] = [];
    const ringArea = (ring: number[][]) => {
      let a = 0;
      for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
        a += (ring[j][0] + ring[i][0]) * (ring[j][1] - ring[i][1]);
      }
      return Math.abs(a) / 2;
    };
    const ringCentre = (ring: number[][]) => {
      let minX = Infinity,
        minY = Infinity,
        maxX = -Infinity,
        maxY = -Infinity;
      for (const [x, y] of ring) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
      return [(minX + maxX) / 2, (minY + maxY) / 2];
    };
    for (const f of (countries as any).features) {
      const g = f.geometry;
      if (!g) continue;
      const polys =
        g.type === "Polygon"
          ? [g.coordinates]
          : g.type === "MultiPolygon"
            ? g.coordinates
            : [];
      let bestRing: number[][] | null = null;
      let bestArea = 0;
      for (const poly of polys) {
        const outer = poly[0];
        if (!outer || outer.length < 3) continue;
        const a = ringArea(outer);
        if (a > bestArea) {
          bestArea = a;
          bestRing = outer;
        }
      }
      if (!bestRing || bestArea < 4) continue;
      const [lng, lat] = ringCentre(bestRing);
      out.push({
        lat,
        lng,
        name: (f.properties?.name || "").toUpperCase(),
        area: bestArea,
      });
    }
    return out;
  }, []);

  // City labels are built from pointClusters directly (NOT pointsData) so
  // identity stays stable across the cluster flip at alt 0.18.
  const cityLabelsData = useMemo(
    () =>
      pointClusters.map((c) => {
        const ids = c.members.map((m) => m.id);
        const cities = Array.from(new Set(c.members.map((m) => m.city)));
        return {
          id: ids.join("+"),
          city: cities.join(" / "),
          country: c.members[0].country,
          lat: c.lat,
          lng: c.lng,
        };
      }),
    [pointClusters],
  );

  const allLabels = useMemo(() => {
    const cities = cityLabelsData.map((p) => ({ ...p, kind: "city" as const }));
    const countriesL = countryLabels.map((c) => ({
      ...c,
      kind: "country" as const,
    }));
    return [...countriesL, ...cities];
  }, [cityLabelsData, countryLabels]);

  // Splash timing: starts once the loading screen is done (isLoaded). Hold
  // ~2.9s, fade out over 600ms, unmount at 3.5s total → then the globe shows.
  useEffect(() => {
    if (!isLoaded) return;
    // Splash crossfades in over the loading screen (~600ms); once opaque,
    // drop the loading screen. Then hold and fade out → globe.
    const hide = setTimeout(() => setHideLoading(true), 700);
    const fade = setTimeout(() => setSplashFading(true), 2900);
    const done = setTimeout(() => setShowSplash(false), 3500);
    return () => {
      clearTimeout(hide);
      clearTimeout(fade);
      clearTimeout(done);
    };
  }, [isLoaded]);

  // Initial view + globe controls
  const handleGlobeReady = useCallback(() => {
    if (globeRef.current) {
      globeRef.current.pointOfView(
        { lat: DEFAULT_LAT, lng: DEFAULT_LNG, altitude: DEFAULT_ALT },
        0,
      );
      const controls = globeRef.current.controls();
      if (controls) {
        controls.autoRotate = false;
        controls.autoRotateSpeed = 0.3;
        controls.enableDamping = true;
        controls.dampingFactor = 0.1;
        controls.enablePan = false;
        controls.touches = { ONE: 0, TWO: 2 };
      }
    }
    // Hold the loading screen for a minimum of 3000ms even when textures are
    // cached, so the kiosk gets a clean intro frame (§H.9) and the loading-bar
    // sweep (3s, see LoadingScreen.FILL_MS) plays out in full.
    setTimeout(() => setIsLoaded(true), 3000);
  }, []);

  // Drive controls.autoRotate from the React state. The state itself is set
  // by the useIdleAttractor sync effect — pause-on-interaction is handled
  // implicitly because any touch wakes the attractor (isIdle → false).
  useEffect(() => {
    if (!globeRef.current) return;
    const controls = globeRef.current.controls();
    if (controls) controls.autoRotate = autoRotate;
  }, [autoRotate, isLoaded]);

  // Camera altitude polling — throttled so React re-renders don't blow up.
  useEffect(() => {
    if (!isLoaded || !globeRef.current) return;
    let rafId: number;
    let lastReported = -1;
    const poll = () => {
      const pov = globeRef.current?.pointOfView?.();
      if (pov && typeof pov.altitude === "number") {
        if (Math.abs(pov.altitude - lastReported) > 0.1) {
          lastReported = pov.altitude;
          setZoomLevel(pov.altitude);
        }
      }
      rafId = requestAnimationFrame(poll);
    };
    rafId = requestAnimationFrame(poll);
    return () => cancelAnimationFrame(rafId);
  }, [isLoaded]);

  const zoomBucket = useMemo(() => bucketForAltitude(zoomLevel), [zoomLevel]);

  // Cable selection — zoom-to-fit the selected cable's landing points.
  const handleSelectCable = useCallback((cable: CableSystem | null) => {
    setSelectedCable(cable);
    setSelectedLandingPoint(null);
    setExpandedPointId(null);
    if (cable && globeRef.current) {
      const points = landingPoints.filter((p) =>
        cable.landingPointIds.includes(p.id),
      );
      if (points.length === 0) return;
      const avgLat = points.reduce((s, p) => s + p.lat, 0) / points.length;
      const avgLng = points.reduce((s, p) => s + p.lng, 0) / points.length;
      const latSpread =
        Math.max(...points.map((p) => p.lat)) -
        Math.min(...points.map((p) => p.lat));
      const lngSpread =
        Math.max(...points.map((p) => p.lng)) -
        Math.min(...points.map((p) => p.lng));
      const spread = Math.max(latSpread, lngSpread);
      const altitude = Math.max(0.4, Math.min(2.8, spread / 18));
      globeRef.current.pointOfView(
        { lat: avgLat, lng: avgLng, altitude },
        1500,
      );
    } else if (!cable && globeRef.current) {
      globeRef.current.pointOfView(
        { lat: DEFAULT_LAT, lng: DEFAULT_LNG, altitude: DEFAULT_ALT },
        1500,
      );
    }
  }, []);

  // Click on a globe point: pick the cluster's first landing point and open
  // the LandingPointCallout. If the cable isn't already selected, also
  // select its first associated cable.
  const handleGlobePointClick = useCallback(
    (point: any) => {
      const memberIds: string[] = point.memberIds || [point.id];
      const lp = landingPoints.find((p) => memberIds.includes(p.id));
      if (!lp) return;
      setSelectedLandingPoint(lp);
      if (!selectedCable && lp.cableIds.length > 0) {
        const first = cablesById[lp.cableIds[0]];
        if (first) setSelectedCable(first);
      }
    },
    [selectedCable],
  );

  const handlePathClick = useCallback(
    (path: PathData) => {
      const cable = cablesById[path.cableId];
      if (cable) handleSelectCable(cable);
    },
    [handleSelectCable],
  );

  // Camera view captured when an info panel opens, so closing can glide back.
  const prevPovRef = useRef<{
    lat: number;
    lng: number;
    altitude: number;
  } | null>(null);

  // Close the expanded info panel and restore the globe to the view it had
  // when the panel was opened (the user may have rotated/zoomed while reading).
  const closeExpanded = useCallback(() => {
    const prev = prevPovRef.current;
    if (prev) {
      globeRef.current?.pointOfView(prev, 700);
      prevPovRef.current = null;
    }
    setExpandedPointId(null);
  }, []);

  // Back button — pops one navigation step:
  //  1. If a landing-point callout is open (location info showing) → close it,
  //     returning to the cable network view. Same as tapping the callout.
  //  2. Otherwise, if a cable is selected → deselect it (resets camera), which
  //     also hides the back button.
  const handleBack = useCallback(() => {
    if (expandedPointId !== null) {
      closeExpanded();
      setSelectedLandingPoint(null);
    } else if (selectedCable) {
      handleSelectCable(null);
    }
  }, [expandedPointId, selectedCable, handleSelectCable, closeExpanded]);

  // Expand a landing-point callout: snapshot the current view, then simply
  // rotate the point to the globe's centre (same altitude — no zoom). The panel
  // anchors above that point, so it ends up centred over the globe with the
  // marker at its bottom. closeExpanded glides back to the snapshot.
  const handleToggleExpand = useCallback(
    (p: LandingPoint) => {
      if (expandedPointId === p.id) {
        closeExpanded();
        return;
      }
      const pov = globeRef.current?.pointOfView?.();
      if (pov && !prevPovRef.current) {
        prevPovRef.current = {
          lat: pov.lat,
          lng: pov.lng,
          altitude: pov.altitude,
        };
      }
      const alt = pov?.altitude ?? DEFAULT_ALT;
      globeRef.current?.pointOfView({ lat: p.lat, lng: p.lng, altitude: alt }, 700);
      setExpandedPointId(p.id);
    },
    [expandedPointId, closeExpanded],
  );

  // Recenter on Malaysia (compass) — leaves selection/dialogs alone.
  const recenterMalaysia = useCallback(() => {
    globeRef.current?.pointOfView(
      { lat: MY_LAT, lng: MY_LNG, altitude: MY_ALT },
      1200,
    );
  }, []);

  // Full reset (RightCluster ⊙) — deselect cable, close callout/dialog,
  // recenter, stop auto-rotate.
  const resetView = useCallback(() => {
    setSelectedCable(null);
    setSelectedLandingPoint(null);
    setOpenDialog(null);
    setExpandedPointId(null);
    prevPovRef.current = null;
    setAutoRotate(false);
    recenterMalaysia();
  }, [recenterMalaysia]);

  // Render order: muted siblings first → halo rings → cores.
  // Later entries in pathsData paint over earlier ones in three-globe, so
  // each core sits on top of its own translucent halo.
  const renderedPaths = useMemo(() => {
    if (!selectedCable) {
      // Nothing selected — every cable gets the neon stack (white-hot core +
      // glow ring) so the network reads consistently "lit up". Each glows in
      // its own colour: active = identity hue, planned = orange, inactive /
      // retired = dim grey.
      const out: PathData[] = [];
      for (const p of pathsData) {
        if (p.color.startsWith("#")) {
          out.push({ ...p, _halo: 2 }, p);
        } else {
          out.push(p);
        }
      }
      return out;
    }
    const others: PathData[] = [];
    const core: PathData[] = [];
    for (const p of pathsData) {
      if (p.cableId === selectedCable.id) core.push(p);
      else others.push(p);
    }
    const halos: PathData[] = [];
    for (const p of core) {
      halos.push({ ...p, _halo: 2 });
    }
    return [...others, ...halos, ...core];
  }, [pathsData, selectedCable]);

  // Path color: selected core → red 3px; selected halos → translucent red;
  // muted siblings (non-selected when a cable is selected) → white 30%, flat;
  // nothing selected → identity colour core + identity-colour translucent halo.
  const getPathColor = useCallback(
    (path: PathData) => {
      if (selectedCable) {
        if (path.cableId !== selectedCable.id) return CABLE_MUTED_COLOR;
        // Selected cable gets the same neon stack, in hot red.
        if (path._halo === 2)
          return hexToRgba(CABLE_SELECTED_COLOR, CABLE_HALO_DEFAULT_OUTER_ALPHA);
        return neonCore(CABLE_SELECTED_COLOR);
      }
      if (path._halo === 2)
        return hexToRgba(path.color, CABLE_HALO_DEFAULT_OUTER_ALPHA);
      return path.color.startsWith("#") ? neonCore(path.color) : path.color;
    },
    [selectedCable],
  );
  const getPathStroke = useCallback(
    (path: PathData) => {
      const s = GLOW_SCALE_BY_BUCKET[zoomBucket];
      if (selectedCable) {
        const isSel = path.cableId === selectedCable.id;
        if (!isSel) return 1;
        // Same neon widths as default, a touch thicker so selection reads.
        if (path._halo === 2) return 4 * s;
        return 1.5;
      }
      if (path._halo === 2) return 3.5 * s;
      return 1;
    },
    [selectedCable, zoomBucket],
  );

  // Point color: highlights cluster members of the selected cable in lime.
  const selectedLPSet = useMemo(
    () => (selectedCable ? new Set(selectedCable.landingPointIds) : null),
    [selectedCable],
  );
  const isPointSelected = useCallback(
    (point: any) => {
      if (!selectedLPSet) return false;
      const ids: string[] = point.memberIds || [point.id];
      return ids.some((id) => selectedLPSet.has(id));
    },
    [selectedLPSet],
  );
  const getPointColor = useCallback(
    (point: any) => {
      if (!selectedLPSet) return LANDING_POINT_DEFAULT;
      if (isPointSelected(point)) return LANDING_POINT_ACTIVE;
      return LANDING_POINT_MUTED;
    },
    [selectedLPSet, isPointSelected],
  );

  const getPointAltitude = useCallback(() => 0.001, []);

  // Stable accessor refs (three-globe is reference-equality based — every new
  // closure looks like a "changed prop" and re-runs the layer's full update).
  const pathPointLat = useCallback((p: any) => p[0], []);
  const pathPointLng = useCallback((p: any) => p[1], []);
  const pathPointAlt = useCallback(() => 0.003, []);
  const labelText = useCallback(
    (l: any) => (l.kind === "country" ? l.name : l.city),
    [],
  );
  const labelColor = useCallback(
    (l: any) =>
      l.kind === "country"
        ? "rgba(180, 200, 230, 0.55)"
        : "rgba(226, 232, 240, 0.85)",
    [],
  );
  const labelSize = useCallback(
    (l: any) =>
      l.kind === "country" ? COUNTRY_LABEL_BASE_SIZE : CITY_LABEL_BASE_SIZE,
    [],
  );
  const labelDotRadius = useCallback(() => 0, []);
  const labelIncludeDot = useCallback(() => false, []);
  const pointRadius = POINT_RADIUS_BY_BUCKET[zoomBucket];

  // Globe sphere material — baked equirectangular dark map routed through
  // emissiveMap so the day/night terminator disappears (mono basemap is
  // already shaded; we want it rendered flat-bright).
  useEffect(() => {
    if (!isLoaded || !globeRef.current) return;
    const id = setTimeout(() => {
      const mat = globeRef.current?.globeMaterial?.();
      if (!mat) return;
      if (mat.map) {
        mat.emissiveMap = mat.map;
        mat.color?.set?.("#000000");
        mat.emissive?.set?.("#ffffff");
        if ("emissiveIntensity" in mat) mat.emissiveIntensity = 1;
      }
      const renderer = globeRef.current?.renderer?.();
      if (renderer && mat.map) {
        const maxAniso = renderer.capabilities?.getMaxAnisotropy?.() ?? 1;
        if (mat.map.anisotropy !== maxAniso) {
          mat.map.anisotropy = maxAniso;
          mat.map.needsUpdate = true;
        }
      }
      mat.needsUpdate = true;
    }, 60);
    return () => clearTimeout(id);
  }, [isLoaded]);

  // Travelling dots — a single InstancedMesh holds one dot per cable segment,
  // all animated continuously regardless of selection. One draw call for every
  // dot (vs a mesh-per-segment); the RAF writes each dot's transform into the
  // shared instance matrix.
  useEffect(() => {
    if (!isLoaded || !globeRef.current) return;
    const scene = globeRef.current.scene?.();
    if (!scene) return;

    const count = dotSegments.length;
    const geo = new THREE.SphereGeometry(DOT_RADIUS, 12, 8);
    const mat = new THREE.MeshBasicMaterial({
      color: new THREE.Color(TRAVELLING_DOT_COLOR),
      // depthTest on so the opaque globe occludes dots on its far side
      // (depthTest:false made back-side dots bleed through to the front).
      depthTest: true,
      transparent: true,
    });
    const inst = new THREE.InstancedMesh(geo, mat, count);
    inst.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
    inst.renderOrder = 999;
    inst.frustumCulled = false;
    scene.add(inst);

    const m4 = new THREE.Matrix4();
    let raf = 0;
    const start = performance.now();
    const tick = () => {
      const elapsedSec = (performance.now() - start) / 1000;
      const pov = globeRef.current?.pointOfView?.();
      const alt = pov?.altitude ?? 1;
      const scale = Math.max(0.12, Math.min(3, (1 + alt) / 2.0));
      for (let i = 0; i < count; i++) {
        const seg = dotSegments[i];
        if (seg.totalKm <= 0) {
          // Degenerate segment — scale to 0 so the instance is invisible.
          m4.makeScale(0, 0, 0);
          inst.setMatrixAt(i, m4);
          continue;
        }
        const speed = Math.min(
          DOT_SPEED_KM_PER_SEC,
          seg.totalKm / DOT_MIN_LOOP_SEC,
        );
        const dist = (elapsedSec * speed) % seg.totalKm;
        let j = 1;
        while (j < seg.cumKm.length && seg.cumKm[j] < dist) j++;
        if (j >= seg.cumKm.length) j = seg.cumKm.length - 1;
        const a = seg.coords[j - 1];
        const b = seg.coords[j];
        const legKm = seg.cumKm[j] - seg.cumKm[j - 1];
        const t = legKm > 0 ? (dist - seg.cumKm[j - 1]) / legKm : 0;
        const lat = a[0] + (b[0] - a[0]) * t;
        const lng = a[1] + (b[1] - a[1]) * t;
        const xyz = globeRef.current.getCoords(lat, lng, 0.005);
        m4.makeScale(scale, scale, scale);
        m4.setPosition(xyz.x, xyz.y, xyz.z);
        inst.setMatrixAt(i, m4);
      }
      inst.instanceMatrix.needsUpdate = true;
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);

    return () => {
      cancelAnimationFrame(raf);
      scene.remove(inst);
      inst.dispose();
      geo.dispose();
      mat.dispose();
    };
  }, [isLoaded, dotSegments]);

  // Regional sharpness overlay (SEA window). Single grid mesh, fades in at
  // close zoom. Always dark in v1.0.
  useEffect(() => {
    if (!isLoaded || !globeRef.current) return;
    const scene = globeRef.current.scene?.();
    if (!scene) return;

    const loader = new THREE.TextureLoader();
    let mesh: THREE.Mesh | null = null;
    let raf = 0;
    let cancelled = false;

    loader.load(SEA_OVERLAY_DARK_URL, (texture) => {
      if (cancelled) {
        texture.dispose();
        return;
      }
      texture.colorSpace = THREE.SRGBColorSpace;
      const renderer = globeRef.current?.renderer?.();
      if (renderer) {
        texture.anisotropy = renderer.capabilities?.getMaxAnisotropy?.() ?? 1;
      }

      const N = SEA_GRID;
      const verts = (N + 1) * (N + 1);
      const positions = new Float32Array(verts * 3);
      const uvs = new Float32Array(verts * 2);
      const indices: number[] = [];

      for (let r = 0; r <= N; r++) {
        const t = r / N;
        const lat = SEA_LAT_MAX + (SEA_LAT_MIN - SEA_LAT_MAX) * t;
        for (let c = 0; c <= N; c++) {
          const u = c / N;
          const lng = SEA_LNG_MIN + (SEA_LNG_MAX - SEA_LNG_MIN) * u;
          const xyz = globeRef.current.getCoords(lat, lng, SEA_OVERLAY_ALT);
          const i = r * (N + 1) + c;
          positions[i * 3] = xyz.x;
          positions[i * 3 + 1] = xyz.y;
          positions[i * 3 + 2] = xyz.z;
          uvs[i * 2] = u;
          uvs[i * 2 + 1] = 1 - t;
        }
      }
      for (let r = 0; r < N; r++) {
        for (let c = 0; c < N; c++) {
          const a = r * (N + 1) + c;
          const b = a + 1;
          const cIdx = a + (N + 1);
          const d = cIdx + 1;
          indices.push(a, cIdx, b, b, cIdx, d);
        }
      }

      const geo = new THREE.BufferGeometry();
      geo.setAttribute("position", new THREE.BufferAttribute(positions, 3));
      geo.setAttribute("uv", new THREE.BufferAttribute(uvs, 2));
      geo.setIndex(indices);

      const mat = new THREE.MeshBasicMaterial({
        map: texture,
        transparent: true,
        opacity: 0,
        depthWrite: false,
      });

      mesh = new THREE.Mesh(geo, mat);
      mesh.renderOrder = 1;
      mesh.frustumCulled = false;
      scene.add(mesh);

      const tick = () => {
        const pov = globeRef.current?.pointOfView?.();
        const alt = pov?.altitude ?? 1;
        const opacity =
          alt >= SEA_FADE_IN_ALT
            ? 0
            : Math.min(
                1,
                (SEA_FADE_IN_ALT - alt) /
                  (SEA_FADE_IN_ALT - SEA_FADE_OUT_ALT),
              );
        mat.opacity = opacity;
        mat.visible = opacity > 0.001;
        raf = requestAnimationFrame(tick);
      };
      raf = requestAnimationFrame(tick);
    });

    return () => {
      cancelled = true;
      cancelAnimationFrame(raf);
      if (mesh) {
        scene.remove(mesh);
        const m = mesh.material as THREE.MeshBasicMaterial;
        m.map?.dispose();
        m.dispose();
        (mesh.geometry as THREE.BufferGeometry).dispose();
      }
    };
  }, [isLoaded]);

  // Per-frame label scaler — both kinds drive visibility + size via
  // mesh.scale on the label Group; TextGeometry is built once and never
  // rebuilt.
  useEffect(() => {
    if (!isLoaded || !globeRef.current) return;
    let raf = 0;
    const tick = () => {
      const pov = globeRef.current?.pointOfView?.();
      const alt = pov?.altitude ?? 1;
      const cityScale = cityScaleAt(alt);
      const countryScale = countryScaleAt(alt);
      for (const label of allLabels) {
        const group = (label as any).__threeObjLabel as
          | { scale: { setScalar: (n: number) => void } }
          | undefined;
        if (!group) continue;
        group.scale.setScalar(
          label.kind === "country" ? countryScale : cityScale,
        );
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [isLoaded, allLabels]);

  // Track screen positions of every landing point along the selected cable.
  // V1.3 Figma intent: when a cable is selected, every one of its landing
  // points renders a callout simultaneously. Throttled to ~30 fps via a
  // frame-skip to avoid a 60Hz React storm.
  useEffect(() => {
    if (!isLoaded || !selectedCable || !globeRef.current) {
      setCalloutScreens({});
      return;
    }
    const points = landingPoints.filter((p) =>
      selectedCable.landingPointIds.includes(p.id),
    );
    let raf = 0;
    let frame = 0;
    const tick = () => {
      frame = (frame + 1) & 1;
      if (frame === 0) {
        const camera: THREE.Camera | null =
          globeRef.current?.camera?.() ?? null;
        const renderer = globeRef.current?.renderer?.();
        if (camera && renderer) {
          const dom = renderer.domElement as HTMLCanvasElement;
          const offX = globeOffsetX(dom.clientWidth);
          const next: Record<string, { x: number; y: number; visible: boolean }> = {};
          for (const p of points) {
            const xyz = globeRef.current.getCoords(p.lat, p.lng, 0.01);
            const v = new THREE.Vector3(xyz.x, xyz.y, xyz.z).project(camera);
            // v.z > 1 = point is behind the camera (far side of the globe)
            const visible = v.z <= 1;
            next[p.id] = {
              x: ((v.x + 1) / 2) * dom.clientWidth + offX,
              y: ((1 - v.y) / 2) * dom.clientHeight,
              visible,
            };
          }
          setCalloutScreens(next);
        }
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [isLoaded, selectedCable]);

  // Cable-scoped landing-point list passed to MorseCodePop.
  const cableLandingPoints = useMemo(() => {
    if (!selectedCable) return [];
    const lookup = new Map(landingPoints.map((p) => [p.id, p]));
    return selectedCable.landingPointIds
      .map((id) => lookup.get(id))
      .filter((p): p is LandingPoint => Boolean(p));
  }, [selectedCable]);

  // Declutter pass: when zoomed out, landing-point callouts pile onto the same
  // patch of screen. Rather than rigidly laddering them apart, run a gentle
  // force relaxation — each box repels overlapping neighbours (in BOTH axes),
  // a soft spring keeps it near its rest spot just above the point, and a clamp
  // stops it straying far. Some overlap is tolerated (ALLOW_*), so dense
  // clusters scatter a little instead of shooting off-screen.
  const calloutLayout = useMemo(() => {
    const W = CALLOUT_WIDTH;
    const H = CALLOUT_BOX_HEIGHT;
    // Closeness 0→1 as the camera zooms in (alt 1.3 → 0.25). Zoomed out we want
    // a gentle nudge; zoomed in, geographically-close points still project to
    // nearly the same pixel, so crank the repel/reach up to fling them apart.
    const closeness = Math.max(0, Math.min(1, (1.3 - zoomLevel) / (1.3 - 0.25)));
    const lerp = (a: number, b: number) => a + (b - a) * closeness;
    // Negative ALLOW = enforce a gap (boxes fully separate); positive = tolerate
    // overlap. Zoomed in we want them fully apart with a small gap.
    const ALLOW_X = lerp(26, -34); // permitted overlap (−gap) before repel; zoomed in = wider horizontal gap
    const ALLOW_Y = lerp(14, -16);
    const REPEL = lerp(0.35, 0.95); // fraction of penetration resolved per step
    const SPRING = lerp(0.1, 0.03); // pull back toward rest (weaker when close)
    const ITER = 22;
    const MAX_OFFSET = lerp(92, 300); // clamp stray from rest

    const items = cableLandingPoints
      .map((p) => ({ id: p.id, s: calloutScreens[p.id] }))
      .filter((it): it is { id: string; s: { x: number; y: number; visible: boolean } } =>
        Boolean(it.s && it.s.visible),
      )
      .sort((a, b) => a.s.x - b.s.x);

    // Rest position = box centre directly above the point. Seed a small,
    // deterministic horizontal jitter so perfectly-stacked points break apart
    // sideways instead of only vertically.
    const nodes = items.map((it, i) => {
      const hx = it.s.x;
      const hy = it.s.y - CALLOUT_REST_RISE;
      const seed = ((i * 53) % 11) - 5; // −5..5 px
      return { id: it.id, hx, hy, cx: hx + seed, cy: hy };
    });

    for (let iter = 0; iter < ITER; iter++) {
      for (let i = 0; i < nodes.length; i++) {
        for (let j = i + 1; j < nodes.length; j++) {
          const a = nodes[i];
          const b = nodes[j];
          let dxc = a.cx - b.cx;
          let dyc = a.cy - b.cy;
          const penX = W - ALLOW_X - Math.abs(dxc);
          const penY = H - ALLOW_Y - Math.abs(dyc);
          if (penX > 0 && penY > 0) {
            if (dxc === 0 && dyc === 0) {
              dxc = i - j; // deterministic tie-break for coincident centres
              dyc = -1;
            }
            const pen = Math.min(penX, penY);
            const len = Math.hypot(dxc, dyc) || 1;
            const push = (REPEL * pen) / 2;
            const nx = (dxc / len) * push;
            const ny = (dyc / len) * push;
            a.cx += nx;
            a.cy += ny;
            b.cx -= nx;
            b.cy -= ny;
          }
        }
      }
      for (const n of nodes) {
        n.cx += (n.hx - n.cx) * SPRING;
        n.cy += (n.hy - n.cy) * SPRING;
        const ox = n.cx - n.hx;
        const oy = n.cy - n.hy;
        const d = Math.hypot(ox, oy);
        if (d > MAX_OFFSET) {
          n.cx = n.hx + (ox / d) * MAX_OFFSET;
          n.cy = n.hy + (oy / d) * MAX_OFFSET;
        }
      }
    }

    const layout: Record<string, { dx: number; dy: number }> = {};
    for (const n of nodes) {
      // Offset of the box centre relative to the POINT (rest is dy = −rise).
      layout[n.id] = { dx: n.cx - n.hx, dy: n.cy - n.hy - CALLOUT_REST_RISE };
    }
    return layout;
  }, [calloutScreens, cableLandingPoints, zoomLevel]);

  return (
    <div
      className="relative w-full h-screen overflow-hidden"
      style={{ background: "var(--v1-bg)", touchAction: "none" }}
    >
      {!hideLoading && <LoadingScreen language={language} />}
      {isLoaded && showSplash && (
        <SplashScreen language={language} fadingOut={splashFading} />
      )}

      <div
        style={{
          transform: `translateX(${globeOffsetX(dimensions.width)}px)`,
          willChange: "transform",
        }}
      >
        <Globe
          ref={globeRef}
          width={dimensions.width}
          height={dimensions.height}
        backgroundColor="#040E1F"
        globeImageUrl={WORLD_MAP_DARK_URL}
        showAtmosphere={true}
        atmosphereColor={ATMOSPHERE_COLOR}
        atmosphereAltitude={0.18}
        pathsData={renderedPaths}
        pathPoints="coords"
        pathPointLat={pathPointLat}
        pathPointLng={pathPointLng}
        pathPointAlt={pathPointAlt}
        pathColor={getPathColor as any}
        pathStroke={getPathStroke as any}
        pathResolution={0.05}
        pathTransitionDuration={0}
        pathLabel={renderPathLabel}
        onPathClick={handlePathClick as any}
        pointsData={pointsData}
        pointLat="lat"
        pointLng="lng"
        pointColor={getPointColor as any}
        pointAltitude={getPointAltitude as any}
        pointRadius={pointRadius}
        pointLabel={renderPointLabel}
        onPointClick={handleGlobePointClick}
        labelsData={allLabels}
        labelLat="lat"
        labelLng="lng"
        labelText={labelText}
        labelColor={labelColor}
        labelSize={labelSize}
        labelDotRadius={labelDotRadius}
        labelAltitude={0.005}
        labelResolution={1}
        labelTypeFace={robotoMedium as any}
        labelIncludeDot={labelIncludeDot}
          onGlobeReady={handleGlobeReady}
          animateIn={true}
        />
      </div>

      {/* Top-right: CableSystem panel (filter tabs + 3x3 grid + counts) */}
      <Sidebar
        selectedCable={selectedCable}
        onSelectCable={handleSelectCable}
        language={language}
      />

      {/* Left of Cable System panel: Back / Audio / Naration button column.
          Back shows only when a cable is selected. */}
      <SystemButtons
        showBack={Boolean(selectedCable)}
        onBack={handleBack}
        muted={muted}
        onAudioToggle={() => setMuted((m) => !m)}
      />

      {/* Bottom-center: language toggle + re-center button (Figma V1.3).
          Audio mute moved to the SystemButtons column beside Cable System. */}
      <div
        style={{
          position: "fixed",
          bottom: 30,
          left: "50%",
          transform: "translateX(-50%)",
          zIndex: 25,
          display: "flex",
          gap: 14,
          alignItems: "center",
        }}
      >
        <LanguageToggle value={language} onChange={setLanguage} />
        <RecenterButton onRecenter={resetView} />
      </div>

      {/* Left edge centered: action cluster (Morse / Fun Fact / Help) */}
      <div
        style={{
          position: "fixed",
          top: "50%",
          left: 26,
          transform: "translateY(-50%)",
          zIndex: 25,
        }}
      >
        <RightCluster
          openDialog={openDialog}
          onOpen={(id) =>
            setOpenDialog((current) => (current === id ? null : id))
          }
          cableSelected={Boolean(selectedCable)}
        />
      </div>

      {/* Right edge: CableInformation when a cable is selected, otherwise the
          General Information panel sits in the same slot above Cable System. */}
      {selectedCable ? (
        <CableInformation cable={selectedCable} language={language} />
      ) : (
        <GeneralInformation language={language} />
      )}

      {/* Bottom: titlebar */}
      <Header selectedCable={selectedCable} language={language} />

      {/* Map overlay: one callout per landing point on the selected cable.
          Tapping a callout expands it; siblings dim while expanded.
          Hidden during an active call so the dialing animation is unobstructed. */}
      {selectedCable &&
        !activeCall &&
        cableLandingPoints.map((p) => {
          const pos = calloutScreens[p.id];
          if (!pos || !pos.visible) return null;
          const isExpanded = expandedPointId === p.id;
          const someoneExpanded = expandedPointId !== null;
          const slot = calloutLayout[p.id];
          return (
            <LandingPointCallout
              key={p.id}
              point={p}
              screenPos={{ x: pos.x, y: pos.y }}
              viewport={dimensions}
              offset={slot}
              expanded={isExpanded}
              dimmed={someoneExpanded && !isExpanded}
              onToggleExpand={() => handleToggleExpand(p)}
            />
          );
        })}

      {/* Leader line from the active cluster button to its dialog title. */}
      <ClusterStem openDialog={openDialog} viewport={dimensions} />

      {/* Dialogs */}
      {openDialog === "howto" && (
        <HowToGuideDialog
          onClose={() => setOpenDialog(null)}
          language={language}
        />
      )}
      {openDialog === "funfact" && selectedCable && (
        <FunFactDialog
          cable={selectedCable}
          onClose={() => setOpenDialog(null)}
          language={language}
        />
      )}
      {openDialog === "morse" && (
        <MorseCodePop
          cable={selectedCable}
          landingPoints={cableLandingPoints}
          language={language}
          onClose={() => setOpenDialog(null)}
          onSend={(message) => {
            setOpenDialog(null);
            setActiveCall({ message, startedAt: performance.now() });
          }}
        />
      )}

      {activeCall && (
        <CallAnimationOverlay
          message={activeCall.message}
          onDone={() => setActiveCall(null)}
          globeRef={globeRef}
        />
      )}

      {/* Idle attractor hint — overlays everything else, pointer-events: none
          so any touch hits the layer underneath and useIdleAttractor wakes. */}
      {isIdle && isLoaded && (
        <div
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 40,
            pointerEvents: "none",
            display: "flex",
            alignItems: "flex-end",
            justifyContent: "center",
            paddingBottom: "20vh",
          }}
        >
          <span
            className="v1-pulse"
            style={{
              fontFamily: "var(--v1-heading)",
              fontWeight: 500,
              fontSize: 28,
              letterSpacing: "0.30em",
              textTransform: "uppercase",
              color: "var(--v1-fg)",
              padding: "16px 32px",
              background: "rgba(0, 0, 0, 0.45)",
              border: "1px solid rgba(255, 255, 255, 0.25)",
            }}
          >
            {t("tapToBegin")}
          </span>
        </div>
      )}
    </div>
  );
}

// ───────── CallAnimationOverlay ─────────
// Drives the call animation: stitched cable polyline → bright orange pulse
// mesh that traverses source → destination, camera lerps to follow, decoded
// message floats above the pulse, then camera returns to world view on
// arrival. Self-cleaning on unmount; runs once per activeCall instance.
const CALL_PULSE_RADIUS = 0.22;
const CALL_PULSE_SPEED_KM_PER_SEC = 550;
const CALL_FOLLOW_ALT = 0.45;
const CALL_INTRO_ALT = 0.9;
const CALL_RETURN_LAT = 5;
const CALL_RETURN_LNG = 108;
const CALL_RETURN_ALT = 2.2;

function CallAnimationOverlay({
  message,
  onDone,
  globeRef,
}: {
  message: string;
  onDone: () => void;
  globeRef: React.MutableRefObject<any>;
}) {
  const [labelPos, setLabelPos] = useState<{ x: number; y: number } | null>(
    null,
  );
  const [phase, setPhase] = useState<
    "dial" | "connect" | "intro" | "travel" | "arrive" | "return"
  >("dial");
  const returnTriggeredRef = useRef(false);

  useEffect(() => {
    if (!globeRef.current) return;
    const scene = globeRef.current.scene?.();
    const renderer = globeRef.current.renderer?.();
    if (!scene || !renderer) return;

    const route = resolveCallRoute();
    if (route.totalKm <= 0) {
      onDone();
      return;
    }

    const dialMs = 1300;
    const connectMs = 1100;
    const introMs = 800;
    const travelMsLocal =
      (route.totalKm / CALL_PULSE_SPEED_KM_PER_SEC) * 1000;

    playDialing();

    const start = route.coords[0];
    setTimeout(() => {
      playConnect();
      globeRef.current?.pointOfView(
        { lat: start[0], lng: start[1], altitude: CALL_INTRO_ALT },
        connectMs + introMs,
      );
    }, dialMs);

    setTimeout(
      () => playMessage(message, travelMsLocal),
      dialMs + connectMs + introMs,
    );

    const geo = new THREE.SphereGeometry(CALL_PULSE_RADIUS, 16, 12);
    const mat = new THREE.MeshBasicMaterial({
      color: new THREE.Color(V1_COLORS.orangeHot),
      depthTest: false,
      transparent: true,
    });
    const pulse = new THREE.Mesh(geo, mat);
    pulse.renderOrder = 1000;
    pulse.frustumCulled = false;
    scene.add(pulse);

    const haloGeo = new THREE.SphereGeometry(CALL_PULSE_RADIUS * 2.4, 16, 12);
    const haloMat = new THREE.MeshBasicMaterial({
      color: new THREE.Color(V1_COLORS.orange),
      transparent: true,
      opacity: 0.35,
      depthTest: false,
      blending: THREE.AdditiveBlending,
    });
    const halo = new THREE.Mesh(haloGeo, haloMat);
    halo.renderOrder = 999;
    halo.frustumCulled = false;
    scene.add(halo);

    let raf = 0;
    let cancelled = false;
    const preLaunchMs = dialMs + connectMs + introMs;
    const travelMs = travelMsLocal;
    const arriveMs = 1500;
    const returnMs = 1800;
    const startTs = performance.now();

    const camera: THREE.Camera | null = globeRef.current?.camera?.() ?? null;
    const projectToScreen = (xyz: { x: number; y: number; z: number }) => {
      if (!camera) return null;
      const v = new THREE.Vector3(xyz.x, xyz.y, xyz.z).project(camera);
      const dom = renderer.domElement as HTMLCanvasElement;
      const w = dom.clientWidth;
      const h = dom.clientHeight;
      return {
        x: ((v.x + 1) / 2) * w + globeOffsetX(w),
        y: ((1 - v.y) / 2) * h,
      };
    };

    const sampleRoute = (dist: number) => {
      let j = 1;
      while (j < route.cumKm.length && route.cumKm[j] < dist) j++;
      if (j >= route.cumKm.length) j = route.cumKm.length - 1;
      const a = route.coords[j - 1];
      const b = route.coords[j];
      const legKm = route.cumKm[j] - route.cumKm[j - 1];
      const t = legKm > 0 ? (dist - route.cumKm[j - 1]) / legKm : 0;
      return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t] as [
        number,
        number,
      ];
    };

    pulse.visible = false;
    halo.visible = false;

    const tick = () => {
      if (cancelled) return;
      const elapsed = performance.now() - startTs;

      if (elapsed < dialMs) {
        setPhase("dial");
      } else if (elapsed < dialMs + connectMs) {
        setPhase("connect");
      } else if (elapsed < preLaunchMs) {
        setPhase("intro");
      } else if (elapsed < preLaunchMs + travelMs) {
        setPhase("travel");
        if (!pulse.visible) {
          pulse.visible = true;
          halo.visible = true;
        }
        const tt = (elapsed - preLaunchMs) / travelMs;
        const dist = tt * route.totalKm;
        const [lat, lng] = sampleRoute(dist);
        const xyz = globeRef.current.getCoords(lat, lng, 0.012);
        pulse.position.set(xyz.x, xyz.y, xyz.z);
        halo.position.set(xyz.x, xyz.y, xyz.z);
        haloMat.opacity = 0.25 + 0.2 * Math.sin(elapsed / 120);

        const pov = globeRef.current.pointOfView?.();
        if (pov) {
          const alpha = 0.06;
          const nextLat = pov.lat + (lat - pov.lat) * alpha;
          const nextLng = pov.lng + (lng - pov.lng) * alpha;
          const nextAlt =
            pov.altitude + (CALL_FOLLOW_ALT - pov.altitude) * alpha;
          globeRef.current.pointOfView(
            { lat: nextLat, lng: nextLng, altitude: nextAlt },
            0,
          );
        }

        const screen = projectToScreen(xyz);
        if (screen) setLabelPos(screen);
      } else if (elapsed < preLaunchMs + travelMs + arriveMs) {
        setPhase("arrive");
        const last = route.coords[route.coords.length - 1];
        const xyz = globeRef.current.getCoords(last[0], last[1], 0.012);
        pulse.position.set(xyz.x, xyz.y, xyz.z);
        halo.position.set(xyz.x, xyz.y, xyz.z);
        const arriveT = (elapsed - preLaunchMs - travelMs) / arriveMs;
        const flash = 1 + Math.sin(arriveT * Math.PI) * 1.4;
        pulse.scale.setScalar(flash);
        halo.scale.setScalar(flash);
        haloMat.opacity = 0.5 * (1 - arriveT) + 0.2;
        const screen = projectToScreen(xyz);
        if (screen) setLabelPos(screen);
      } else if (elapsed < preLaunchMs + travelMs + arriveMs + returnMs) {
        if (!returnTriggeredRef.current) {
          returnTriggeredRef.current = true;
          setPhase("return");
          globeRef.current.pointOfView(
            {
              lat: CALL_RETURN_LAT,
              lng: CALL_RETURN_LNG,
              altitude: CALL_RETURN_ALT,
            },
            returnMs,
          );
        }
        const rt = (elapsed - preLaunchMs - travelMs - arriveMs) / returnMs;
        mat.opacity = Math.max(0, 1 - rt);
        haloMat.opacity = Math.max(0, 0.4 * (1 - rt));
        setLabelPos(null);
      } else {
        cancelled = true;
        cancelAnimationFrame(raf);
        scene.remove(pulse);
        scene.remove(halo);
        geo.dispose();
        mat.dispose();
        haloGeo.dispose();
        haloMat.dispose();
        onDone();
        return;
      }

      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);

    return () => {
      cancelled = true;
      cancelAnimationFrame(raf);
      scene.remove(pulse);
      scene.remove(halo);
      geo.dispose();
      mat.dispose();
      haloGeo.dispose();
      haloMat.dispose();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      {labelPos && (
        <div
          className="fixed z-30 pointer-events-none"
          style={{
            left: labelPos.x,
            top: labelPos.y - 60,
            transform: "translate(-50%, -100%)",
          }}
        >
          <div
            style={{
              padding: "10px 18px",
              background: "var(--v1-orange)",
              border: "1px solid rgba(255, 255, 255, 0.30)",
              boxShadow: "0 4px 24px rgba(240, 90, 34, 0.55)",
            }}
          >
            <span
              className="v1-h-display"
              style={{
                fontSize: 18,
                color: "var(--v1-fg)",
                letterSpacing: "0.18em",
                whiteSpace: "nowrap",
              }}
            >
              {message}
            </span>
          </div>
          <div
            style={{
              width: 1,
              height: 48,
              background:
                "linear-gradient(180deg, var(--v1-orange) 0%, transparent 100%)",
              margin: "0 auto",
            }}
          />
        </div>
      )}
      <div
        style={{
          position: "fixed",
          top: "40%",
          left: "50%",
          transform: "translateX(-50%)",
          zIndex: 30,
          pointerEvents: "none",
        }}
      >
        {phase === "dial" && (
          <PhaseChip text="Dialing…" tone="orange" pulse />
        )}
        {phase === "connect" && (
          <PhaseChip text="Establishing Link…" tone="blue" />
        )}
        {phase === "intro" && <PhaseChip text="Transmitting" tone="blue" />}
        {phase === "arrive" && <PhaseChip text="Delivered" tone="orange" />}
      </div>
    </>
  );
}

function PhaseChip({
  text,
  tone,
  pulse = false,
}: {
  text: string;
  tone: "orange" | "blue";
  pulse?: boolean;
}) {
  return (
    <div
      className={pulse ? "v1-pulse" : undefined}
      style={{
        padding: "12px 24px",
        background:
          tone === "orange" ? "var(--v1-orange)" : "var(--v1-blue)",
        border: "1px solid rgba(255, 255, 255, 0.40)",
      }}
    >
      <span
        className="v1-h-display"
        style={{
          fontSize: 13,
          color: "var(--v1-fg)",
          letterSpacing: "0.30em",
        }}
      >
        {text}
      </span>
    </div>
  );
}
