// AUTO-GENERATED by scripts/import-landing-images.mjs — do not edit by hand.
// Sources live in assets/landing-points/<id>/ (not served); this maps each
// landing-point id to its web-sized WebP renditions, in drop order.
// Re-run `node scripts/import-landing-images.mjs` after adding images.

export type LandingPointImage = {
  /** Path under public/, ready for <img src>. */
  src: string;
  width: number;
  height: number;
};

/** Landing-point id -> its photos. Ids with no photo are simply absent. */
export const LANDING_POINT_IMAGES: Record<string, LandingPointImage[]> = {
  "alexandria": [
    {
      "src": "/images/landing-points/alexandria/1.webp",
      "width": 1000,
      "height": 500
    }
  ],
  "bayan-baru": [
    {
      "src": "/images/landing-points/bayan-baru/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "bintulu": [
    {
      "src": "/images/landing-points/bintulu/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "cherating": [
    {
      "src": "/images/landing-points/cherating/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "jeram": [
    {
      "src": "/images/landing-points/jeram/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "kota-kinabalu": [
    {
      "src": "/images/landing-points/kota-kinabalu/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "kuala-besut": [
    {
      "src": "/images/landing-points/kuala-besut/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "kuala-perlis": [
    {
      "src": "/images/landing-points/kuala-perlis/1.webp",
      "width": 1000,
      "height": 578
    },
    {
      "src": "/images/landing-points/kuala-perlis/2.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "kuching": [
    {
      "src": "/images/landing-points/kuching/1.webp",
      "width": 1000,
      "height": 563
    },
    {
      "src": "/images/landing-points/kuching/2.webp",
      "width": 1000,
      "height": 562
    }
  ],
  "langkawi": [
    {
      "src": "/images/landing-points/langkawi/1.webp",
      "width": 1000,
      "height": 578
    },
    {
      "src": "/images/landing-points/langkawi/2.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "lumut": [
    {
      "src": "/images/landing-points/lumut/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "merang": [
    {
      "src": "/images/landing-points/merang/1.webp",
      "width": 1000,
      "height": 615
    }
  ],
  "mersing": [
    {
      "src": "/images/landing-points/mersing/1.webp",
      "width": 1000,
      "height": 578
    },
    {
      "src": "/images/landing-points/mersing/2.webp",
      "width": 1000,
      "height": 578
    },
    {
      "src": "/images/landing-points/mersing/3.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "miri": [
    {
      "src": "/images/landing-points/miri/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "pulau-jerejak": [
    {
      "src": "/images/landing-points/pulau-jerejak/1.webp",
      "width": 1000,
      "height": 562
    },
    {
      "src": "/images/landing-points/pulau-jerejak/2.webp",
      "width": 750,
      "height": 414
    },
    {
      "src": "/images/landing-points/pulau-jerejak/3.webp",
      "width": 1000,
      "height": 578
    },
    {
      "src": "/images/landing-points/pulau-jerejak/4.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "pulau-ketam": [
    {
      "src": "/images/landing-points/pulau-ketam/1.webp",
      "width": 1000,
      "height": 466
    }
  ],
  "pulau-pangkor": [
    {
      "src": "/images/landing-points/pulau-pangkor/1.webp",
      "width": 1000,
      "height": 750
    }
  ],
  "pulau-perhentian": [
    {
      "src": "/images/landing-points/pulau-perhentian/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "pulau-redang": [
    {
      "src": "/images/landing-points/pulau-redang/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "pulau-tioman": [
    {
      "src": "/images/landing-points/pulau-tioman/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "rompin": [
    {
      "src": "/images/landing-points/rompin/1.webp",
      "width": 1000,
      "height": 578
    }
  ],
  "seberang-jaya": [
    {
      "src": "/images/landing-points/seberang-jaya/1.webp",
      "width": 1000,
      "height": 563
    },
    {
      "src": "/images/landing-points/seberang-jaya/2.webp",
      "width": 1000,
      "height": 642
    }
  ],
  "sg-lima": [
    {
      "src": "/images/landing-points/sg-lima/1.webp",
      "width": 1000,
      "height": 560
    }
  ]
};
